[package]
name = "api-error-derive"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
api-error = { path = "../api-error" }

[dev-dependencies]
compiletest_rs = "0.3"
